apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: boilerplate-map
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - hutchdev.ca
    - www.hutchdev.ca
    secretName: tls-secret
  rules:
  - host: hutchdev.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: boilerplate-service
          servicePort: 80
  - host: www.hutchdev.ca
    http:
      paths:
        - path: /
          backend:
            serviceName: boilerplate-service
            servicePort: 80
