apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boilerplate-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: react-boilerplate
    spec:
      containers:
      - name: react-boilerplate
        image: hutchgrant/react-boilerplate:latest
        command: ['bash', '-c', 'npm run start']
        ports:
        - name: nodejs-port
          containerPort: 5000
        envFrom:
        - secretRef:
            name: mysecret
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-service
  labels:
    app: react-boilerplate
spec:
  ports:
    - port: 80
      name: http
      targetPort: nodejs-port
  selector:
    app: react-boilerplate