version: '3.1'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    labels: 
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs:ro 
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
  redis:
    image: redis:alpine
    volumes:
      - data-redis:/data
  mongo:
    image: mongo
    volumes:
      - data-mongo:/data/db
  node:
    image: hutchgrant/react-boilerplate
    command: npm start
    ports:
      - "5000"
    env_file:
      - ./config/prod.env
    environment:
      - NODE_ENV=production
    depends_on:
      - nginx-proxy-companion
      - mongo
      - redis
volumes:
    certs:
    data-mongo:
    data-redis:
    nginx-vhost:
    nginx-html: