apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hutchdev-ca
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: hutchdev.ca
  dnsNames:
  - hutchdev.ca
  - www.hutchdev.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - hutchdev.ca
      - www.hutchdev.ca
