apiVersion: v1
kind: Namespace
metadata:
  name: main
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: main
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: launcher.gcr.io/google/redis3:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  namespace: main
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: main
spec:
  ports:
  - name: redis-port
    port: 6379
  selector:
    app: redis
