apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: ingress-nginx 
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 31001
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    nodePort: 32001
    protocol: TCP
    targetPort: 443
  selector:
    app: ingress-nginx