kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  namespace: main
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
