apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: main
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: launcher.gcr.io/google/mongodb3
        name: mongo
        volumeMounts:
          - name: data
            mountPath: /data/db
            subPath: data
        args:
          - '--auth'
        ports:
        - containerPort: 27017
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
